vagrant:
    api_version: "2"

vm:
    box: "ubuntu-trusty-amd64"
#    box_url: "https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"
    box_url: "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
    hostname: null
    usable_port_range: 2200..2500
    network:
        private_network: 192.168.100.100
        forwarded_ports:
            # ssh is set by default - overwriting it can lead to unexpected behavior
            #ssh:
            #    host: 2222
            #    guest: 22
            http_8080:
                host: 8080
                guest: 80
            http_8000:
                host: 8000
                guest: 8000
            php:
                host: 9000
                guest: 9000
    provider:
        virtualbox:
            memory: 2048
            cpus: 2
            modifyvm:
                name: devmachine
                # natdnsproxy1: true
                natdnshostresolver1: true
                # rtcuseutc: true # bugfix ssh connection - https://github.com/mitchellh/vagrant/issues/391
                memory: 2048
            gui: false
            setextradata:
                VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: true # enable symlinks for windows
            check_guest_additions: false
            functional_vboxsf: false
    provision: {}

ssh:
    host: null
    port: null
    private_key_path: null
    username: vagrant # https://github.com/Varying-Vagrant-Vagrants/VVV/issues/375
    guest_port: null
    keep_alive: true
    forward_agent: false # http://wildlyinaccurate.com/using-ssh-agent-forwarding-with-vagrant/
    forward_x11: false
    shell: "bash -c 'BASH_ENV=/etc/profile exec bash'" # default: "bash -l", but this resolves the stdin error

devmachine:
    bashrc: "cd /env"
    ip: 192.168.100.100
    timezone: Europe/Brussels
    locale: en_US.UTF-8
    shell: bash
    docker:
        version: 1.8.2*
        group_members: vagrant
    docker-compose:
        version: 1.3.3
    ansible:
        version: 1.9.2
        playbook: /env/ansible/playbook.yml
        extra_vars: {}