mysql56:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: docker
    MYSQL_PASSWORD: docker
    MYSQL_DATABASE: docker
  ports:
    - "3306"
  command: ""

php54fpm:
  build: /env/docker/php54-fpm
  ports:
    - "9000"

php55fpm:
  build: /env/docker/php55-fpm
  ports:
    - "9000"

php56fpm:
  build: /env/docker/php56-fpm
  ports:
    - "9000"

php70fpm:
  build: /env/docker/php70-fpm
  ports:
    - "9000"

apache24:
  build: /env/docker/apache24
  environment:
    - APACHE_RUN_USER="www-data"
    - APACHE_RUN_GROUP="www-data"
    - APACHE_PID_FILE="/var/run/apache2/apache2.pid"
    - APACHE_RUN_DIR="/var/run/apache2"
#    - APACHE_LOCK_DIR="/var/lock/apache2" # TODO
#    - APACHE_LOG_DIR="/log" # TODO
    - APACHE_SERVERADMIN="admin@localhost"
    - APACHE_SERVERNAME="localhost"
    - APACHE_HOST="*"
    - APACHE_PORT="80"
    - APACHE_DOCUMENTROOT="/var/www/html"
  ports:
    - "80"
    - "443"
  command: -DFOREGROUND