data:
  image: busybox
  volumes:
    - /env/workspace:/var/www/html
    - /env/workspace/devmachine/log:/log
    # TODO - /env/mysql:/var/lib/mysql
  command: "true"

db:
  extends:
    file: /env/docker/common.yml
    service: mysql56
  environment:
    MYSQL_USER: devmachine
    MYSQL_PASSWORD: devmachine
    MYSQL_DATABASE: devmachine
  ports:
    - "3306"
  volumes_from:
    - data

php:
  extends:
    file: /env/docker/common.yml
    service: php54fpm
  links:
    - db:db
  volumes_from:
    - data

lamp:
  extends:
    file: /env/docker/common.yml
    service: apache24
  links:
    - php:php
    - db:db
  environment:
    - APACHE_SERVER_NAME=devmachine
    - APACHE_SERVER_ADMIN=metalarend@gmail.com
    - APACHE_DOCUMENT_ROOT=/var/www/html/devmachine/public
    - WORK_DIR=/var/www/html/devmachine
  ports:
    - "8080:80"
  volumes_from:
    - data