data:
  image: busybox
  volumes:
    - /env/workspace/devmachine:/var/www
    - /env/workspace/stagesol/app/logs:/log
    # TODO - /env/mysql:/var/lib/mysql
  command: "true"

db:
  extends:
    file: /env/docker/common.yml
    service: mysql56
  environment:
    MYSQL_USER: devmachine
    MYSQL_PASSWORD: devmachine
    MYSQL_DATABASE: devmachine
  ports:
    - "3306"
  volumes_from:
    - data

php:
  extends:
      file: /env/docker/common.yml
      service: php54fpm
  links:
    - db:db
  volumes_from:
    - data

lamp54:
  extends:
    file: /env/docker/common.yml
    service: apache24
  links:
    - php:php
    - db:db
  ports:
    - "8080:80"
  volumes_from:
    - data