---
- hosts: all
  sudo: true
  vars:
    web_server: nginxphp
    servername: haphpy-birthday.dev www.haphpy-birthday.dev 192.168.33.99
    timezone: UTC
  vars_files:
    - vars/common.yml
  roles:
    - init
    - mariadb-server
    - apache
    - php7
    - composer
    - app
